import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import {
  FaShoppingCart,
  FaUser,
  FaSearch,
  FaFacebookF,
  FaTwitter,
  FaInstagram,
  FaHome,
  FaInfoCircle,
  FaTag,
  FaEnvelope,
} from "react-icons/fa";
import CategoryNav from "./CatergoryNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="bg-white shadow-md">
          <div className="container mx-auto px-4 py-6">
            <div className="flex flex-wrap justify-between items-center">
              <div className="flex items-center mb-4 md:mb-0">
                <Link href="/home">
                  <span className="text-xl font-bold text-red-600">
                    BookBank
                  </span>
                </Link>
              </div>
              <div className="w-full md:w-auto mb-4 md:mb-0 md:mr-5 md:ml-auto">
                <div className="relative">
                  <input
                    type="text"
                    placeholder="Search books..."
                    className="w-full px-4 py-2 pl-10 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-red-600"
                  />
                  <FaSearch className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400" />
                </div>
              </div>
              <div className="flex items-center space-x-4">
                <nav className="hidden md:block">
                  <ul className="flex flex-wrap justify-center space-x-4">
                    <li>
                      <Link href="/home">
                        <span className="text-gray-800 hover:text-red-600 flex items-center">
                          <FaHome className="mr-1" />
                          Home
                        </span>
                      </Link>
                    </li>
                    <li>
                      <Link href="/about">
                        <span className="text-gray-800 hover:text-red-600 flex items-center">
                          <FaInfoCircle className="mr-1" />
                          About
                        </span>
                      </Link>
                    </li>
                    <li>
                      <Link href="/deals">
                        <span className="text-gray-800 hover:text-red-600 flex items-center">
                          <FaTag className="mr-1" />
                          Deals
                        </span>
                      </Link>
                    </li>
                    <li>
                      <Link href="/contact">
                        <span className="text-gray-800 hover:text-red-600 flex items-center">
                          <FaEnvelope className="mr-1" />
                          Contact
                        </span>
                      </Link>
                    </li>
                  </ul>
                </nav>
                <Link href="/cart">
                  <span className="text-gray-800 hover:text-red-600 flex items-center">
                    <FaShoppingCart className="mr-1" />
                    Cart
                  </span>
                </Link>
                <Link href="/login">
                  <span className="text-gray-800 hover:text-red-600 flex items-center">
                    <FaUser className="mr-1" />
                    Login
                  </span>
                </Link>
              </div>
            </div>
            <nav className="md:hidden mt-4">
              <ul className="flex flex-wrap justify-center space-x-4">
                <li>
                  <Link href="/home">
                    <span className="text-gray-800 hover:text-red-600 flex items-center">
                      <FaHome className="mr-1" />
                      Home
                    </span>
                  </Link>
                </li>
                <li>
                  <Link href="/about">
                    <span className="text-gray-800 hover:text-red-600 flex items-center">
                      <FaInfoCircle className="mr-1" />
                      About
                    </span>
                  </Link>
                </li>
                <li>
                  <Link href="/deals">
                    <span className="text-gray-800 hover:text-red-600 flex items-center">
                      <FaTag className="mr-1" />
                      Deals
                    </span>
                  </Link>
                </li>
                <li>
                  <Link href="/contact">
                    <span className="text-gray-800 hover:text-red-600 flex items-center">
                      <FaEnvelope className="mr-1" />
                      Contact
                    </span>
                  </Link>
                </li>
              </ul>
            </nav>
          </div>
        </header>
        <CategoryNav />
        {children}
        <footer className="bg-white shadow-md mt-8">
          <div className="container mx-auto px-4 py-6">
            <div className="flex flex-col md:flex-row justify-between items-center">
              <div className="mb-4 md:mb-0">
                <Link href="/">
                  <span className="text-xl font-bold text-red-600">
                    BookStore
                  </span>
                </Link>
              </div>
              <nav className="mb-4 md:mb-0">
                <ul className="flex flex-col md:flex-row space-y-2 md:space-y-0 md:space-x-4 text-center md:text-left">
                  <li>
                    <Link href="/home">
                      <span className="text-gray-800 hover:text-red-600">
                        Home
                      </span>
                    </Link>
                  </li>
                  <li>
                    <Link href="/about">
                      <span className="text-gray-800 hover:text-red-600">
                        About
                      </span>
                    </Link>
                  </li>
                  <li>
                    <Link href="/contact">
                      <span className="text-gray-800 hover:text-red-600">
                        Contact
                      </span>
                    </Link>
                  </li>
                  <li>
                    <Link href="/terms">
                      <span className="text-gray-800 hover:text-red-600">
                        Terms &amp; Conditions
                      </span>
                    </Link>
                  </li>
                </ul>
              </nav>
              <div className="mt-4 md:mt-0">
                <ul className="flex space-x-4 justify-center md:justify-end">
                  <li>
                    <a
                      href="https://www.facebook.com"
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      <FaFacebookF className="text-gray-800 hover:text-red-600" />
                    </a>
                  </li>
                  <li>
                    <a
                      href="https://www.twitter.com"
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      <FaTwitter className="text-gray-800 hover:text-red-600" />
                    </a>
                  </li>
                  <li>
                    <a
                      href="https://www.instagram.com"
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      <FaInstagram className="text-gray-800 hover:text-red-600" />
                    </a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
          <div className="bg-red-600 py-2">
            <div className="container mx-auto px-4 text-center text-white">
              &copy; {new Date().getFullYear()} BookStore. All rights reserved.
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
